---
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
script: bundle exec rake test
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
env:
  - PUPPET_VERSION="3.4.3"
  - PUPPET_VERSION="3.5.1" STRICT_VARIABLES=yes
  - PUPPET_VERSION="3.6.2" STRICT_VARIABLES=yes
  - PUPPET_VERSION="3.7.1" STRICT_VARIABLES=yes
  - PUPPET_VERSION="3.7.1" STRICT_VARIABLES=yes FUTURE_PARSER=yes

matrix:
  fast_finish: true
  exclude:
    - rvm: 2.1.0
      env: PUPPET_VERSION="3.4.3"

notifications:
  email: false

deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: "DUZUJuAFjY078gBQvtSUo8JhVg722Me+Ow/OA7xCAa3/QbBv3Tq/DZreRMU6FsEaZiRzB99Cc38XtIM9T35PzVde4fKMXGW49dd1wF3/P9ei22b1PWAY+WlvAtC13LM7Re7UDYEJYMwPrLdizEHu2yHsyCH4M5Q75NDy5rC7mrQ="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish if our main Ruby target builds
    rvm: 1.9.3
